/**
 * Options Page Entry Point
 * Handles initialization, state management, and event handling for the options page
 */

import {
  loadToolConfigurationForOptions,
  resetToDefault,
  saveToolOrder,
  toggleToolEnabled,
} from './lib/optionsStateManager';
import type { UserPreferences } from './lib/types';
import { ToolList } from './options/components/ToolList';
import * as logger from './utils/logger';
import './options/styles/options.css';

// Global state
let toolListComponent: ToolList | null = null;
let currentPreferences: UserPreferences | null = null;

// DOM elements
let warningBanner: HTMLElement | null = null;
let warningCloseButton: HTMLElement | null = null;
let resetButton: HTMLElement | null = null;
let toolListContainer: HTMLElement | null = null;

/**
 * Creates the main HTML structure
 */
function createHTML(): void {
  document.body.innerHTML = `
    <!-- Warning Banner (Hidden by Default) -->
    <div
      id="__github-switcher-warning-banner"
      class="__github-switcher-warning-banner"
      role="alert"
      aria-live="assertive"
    >
      <div class="__github-switcher-warning-banner-content">
        <span class="__github-switcher-warning-banner-icon">⚠️</span>
        <p class="__github-switcher-warning-banner-message">
          检测到数据损坏，已自动恢复到默认设置。
          <br />
          Data corruption detected. Settings have been automatically restored to defaults.
        </p>
        <button
          id="__github-switcher-warning-close"
          class="__github-switcher-warning-banner-close"
          aria-label="关闭警告"
        >
          ✕
        </button>
      </div>
    </div>

    <!-- Main Container -->
    <div class="__github-switcher-options-container">
      <!-- Header -->
      <header class="__github-switcher-options-header">
        <h1>GitHub Switcher - 工具管理</h1>
        <p class="__github-switcher-options-subtitle">
          拖拽调整工具顺序，点击开关启用/禁用工具
          <br />
          Drag to reorder tools, toggle switches to enable/disable
        </p>
      </header>

      <!-- Tool List Section -->
      <section class="__github-switcher-options-section">
        <h2 class="__github-switcher-options-section-title">工具列表 / Tool List</h2>
        <div
          id="__github-switcher-tool-list"
          class="__github-switcher-tool-list"
          role="list"
        >
          <!-- Tool items will be dynamically generated by ToolList.ts -->
        </div>
      </section>

      <!-- Preview Section -->
      <section class="__github-switcher-options-section">
        <h2 class="__github-switcher-options-section-title">预览 / Preview</h2>
        <div
          class="__github-switcher-preview-area"
          aria-label="工具菜单预览"
        >
          <!-- Preview content will be dynamically generated -->
        </div>
      </section>

      <!-- Footer with Reset Button -->
      <footer class="__github-switcher-options-footer">
        <button
          id="__github-switcher-reset-button"
          class="__github-switcher-reset-button"
          aria-label="重置为默认配置 / Reset to defaults"
        >
          重置为默认 / Reset to Defaults
        </button>
      </footer>
    </div>
  `;
}

/**
 * Initializes the options page
 */
async function initialize(): Promise<void> {
  logger.log('[Options] Initializing...');

  try {
    // Create HTML structure
    createHTML();

    // Load DOM elements
    warningBanner = document.getElementById('__github-switcher-warning-banner');
    warningCloseButton = document.getElementById('__github-switcher-warning-close');
    resetButton = document.getElementById('__github-switcher-reset-button');
    toolListContainer = document.getElementById('__github-switcher-tool-list');

    if (!toolListContainer) {
      throw new Error('Tool list container not found');
    }

    // Load user preferences
    const result = await loadToolConfigurationForOptions();
    currentPreferences = result.config;

    // Show warning banner if data was corrupted
    if (result.hasWarning && warningBanner) {
      warningBanner.classList.add('__github-switcher-warning-banner--visible');
    }

    // Initialize tool list component
    toolListComponent = new ToolList();
    toolListComponent.mount(toolListContainer, currentPreferences);

    // Set up event handlers
    setupEventHandlers();

    logger.log('[Options] Initialization complete', {
      toolCount: currentPreferences.toolOrder?.length || 9,
      enabledCount: currentPreferences.enabledTools.length,
      hasWarning: result.hasWarning,
    });
  } catch (error) {
    logger.error('[Options] Initialization failed:', error);
    showError('Failed to load options. Please try refreshing the page.');
  }
}

/**
 * Sets up all event handlers
 */
function setupEventHandlers(): void {
  // Warning banner close button
  if (warningCloseButton) {
    warningCloseButton.addEventListener('click', () => {
      if (warningBanner) {
        warningBanner.classList.remove('__github-switcher-warning-banner--visible');
      }
    });
  }

  // Reset button
  if (resetButton) {
    resetButton.addEventListener('click', handleReset);
  }

  // Tool toggle handler
  if (toolListComponent) {
    toolListComponent.onToggle(handleToolToggle);
    toolListComponent.onDragEnd(handleDragEnd);
  }
}

/**
 * Handles drag end events (tool reordering)
 */
async function handleDragEnd(newOrder: number[]): Promise<void> {
  if (!currentPreferences) {
    logger.error('[Options] No preferences loaded');
    return;
  }

  try {
    logger.log('[Options] Saving new tool order:', newOrder);

    // Save new order
    await saveToolOrder(newOrder);

    // Reload preferences
    const result = await loadToolConfigurationForOptions();
    currentPreferences = result.config;

    logger.log('[Options] Tool order saved successfully');
  } catch (error) {
    logger.error('[Options] Failed to save tool order:', error);
    const errorMessage =
      error instanceof Error ? error.message : 'Failed to save tool order. Please try again.';
    showError(errorMessage);

    // Reload and revert UI
    const result = await loadToolConfigurationForOptions();
    currentPreferences = result.config;
    if (toolListComponent) {
      toolListComponent.update(currentPreferences);
    }
  }
}

/**
 * Handles tool toggle events
 */
async function handleToolToggle(toolId: number, enabled: boolean): Promise<void> {
  if (!currentPreferences) {
    logger.error('[Options] No preferences loaded');
    return;
  }

  try {
    logger.log('[Options] Toggling tool:', { toolId, enabled });

    // Update preferences (throws on error)
    await toggleToolEnabled(toolId, enabled);

    // Reload preferences
    const result = await loadToolConfigurationForOptions();
    currentPreferences = result.config;

    // Update UI
    if (toolListComponent) {
      toolListComponent.update(currentPreferences);
    }

    logger.log('[Options] Tool toggled successfully', {
      toolId,
      enabled,
      enabledCount: currentPreferences.enabledTools.length,
    });
  } catch (error) {
    logger.error('[Options] Toggle failed:', error);
    const errorMessage =
      error instanceof Error ? error.message : 'Failed to update tool state. Please try again.';
    showError(errorMessage);

    // Reload and revert UI
    const result = await loadToolConfigurationForOptions();
    currentPreferences = result.config;
    if (toolListComponent) {
      toolListComponent.update(currentPreferences);
    }
  }
}

/**
 * Handles reset button click
 */
async function handleReset(): Promise<void> {
  // Confirm action
  const confirmed = window.confirm(
    '确定要重置所有设置到默认值吗？此操作无法撤销。\n\nAre you sure you want to reset all settings to defaults? This action cannot be undone.'
  );

  if (!confirmed) {
    return;
  }

  try {
    logger.log('[Options] Resetting to defaults...');

    // Reset preferences (throws on error)
    await resetToDefault();

    // Reload preferences
    const result = await loadToolConfigurationForOptions();
    currentPreferences = result.config;

    // Update UI
    if (toolListComponent) {
      toolListComponent.update(currentPreferences);
    }

    logger.log('[Options] Reset complete');
    showSuccess('设置已重置到默认值 / Settings have been reset to defaults');
  } catch (error) {
    logger.error('[Options] Reset failed:', error);
    showError('Failed to reset settings. Please try again.');
  }
}

/**
 * Shows an error message
 */
function showError(message: string): void {
  // TODO: Implement toast notification in Phase 2
  // For now, use alert
  window.alert(`❌ ${message}`);
}

/**
 * Shows a success message
 */
function showSuccess(message: string): void {
  // TODO: Implement toast notification in Phase 2
  // For now, use alert
  window.alert(`✅ ${message}`);
}

/**
 * Main entry point
 */
document.addEventListener('DOMContentLoaded', () => {
  initialize().catch((error) => {
    logger.error('[Options] Fatal error:', error);
    showError('Failed to initialize options page. Please reload the extension.');
  });
});

/**
 * Default export required by Plasmo to detect this as an options page
 * This function is never called - Plasmo just needs the default export
 * Actual rendering happens via DOM manipulation in initialize()
 */
export default function OptionsPage() {
  return null;
}
